using System.Collections.Generic;
using System.Linq;

namespace MhbWasmSQLite.Client.Features.FavoriteVerses;

public class FavoriteVersesFactory
{
	public static IQueryable<FavoriteVerse> GetAll()
	{
		/*
		 PartialView = "Gen_1_1", 
		 ScriptureIdBeg = 1, ScriptureIdEnd = 1, BookID = 1, 
		 VerseName = "Genesis 1:1", VerseNameAbrv = "Gen 1:1", 
		 VerseDescription = "Creation", 
		 Commentary = "Arguably the most important verse in scripture", 
		 HasExtraInfo = true
		 * 
	 */
		return new List<FavoriteVerse>
		 {
			new FavoriteVerse() { PartialView = "Gen_1_1", ScriptureIdBeg = 1, ScriptureIdEnd = 1, BookID = 1, VerseName = "Genesis 1:1", VerseNameAbrv = "Gen 1:1", VerseDescription = "Creation", Commentary = "Arguably the most important verse in scripture", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Gen_3_12_to_17", ScriptureIdBeg = 68, ScriptureIdEnd = 73, BookID = 1, VerseName = "Genesis 3:12-17", VerseNameAbrv = "Gen 3:12-17", VerseDescription = "Adam projects his problems on the woman and God", Commentary = "This is the proximate cause of why we Adamites have found ourselves in &quot;the Bizarro world&quot;.", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Gen_4_9_to_14", ScriptureIdBeg = 89, ScriptureIdEnd = 94, BookID = 1, VerseName = "Genesis 4:9-14", VerseNameAbrv = "Gen 4:9-14", VerseDescription = "Brother&quot;s Keeper", Commentary = "Are you your brother&quot;s keeper", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Gen_12_1_to_2", ScriptureIdBeg = 300, ScriptureIdEnd = 301, BookID = 1, VerseName = "Genesis 12:1-2", VerseNameAbrv = "Gen 12:1-2", VerseDescription = "God calls Abram", Commentary = "A promise from God to Abram was made, was this conditional", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Gen_15_12_to_17", ScriptureIdBeg = 373, ScriptureIdEnd = 378, BookID = 1, VerseName = "Genesis 15:12-17", VerseNameAbrv = "Gen 15:12-17", VerseDescription = "The estate for Abram is created", Commentary = "These verses bring up interesting questions with regard to what makes up the necessary elements of a contract/covenant", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Gen_49_10", ScriptureIdBeg = 1484, ScriptureIdEnd = 1484, BookID = 1, VerseName = "Genesis 49:10", VerseNameAbrv = "Gen 49:10", VerseDescription = "Until Shiloh cometh, the sceptre, Judah, giver of law", Commentary = "This has law written all over it, but what does it mean???", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Exo_15_18", ScriptureIdBeg = 1939, ScriptureIdEnd = 1939, BookID = 2, VerseName = "Exodus 15:18", VerseNameAbrv = "Exo 15:18", VerseDescription = "YHVH is the King of Israel", Commentary = "These needs to be contrasted to what happened in 1<sup>st</sup> chapter 8, and latter on in the Declaration of Independence", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Exo_19_3_to_6", ScriptureIdBeg = 2030, ScriptureIdEnd = 2033, BookID = 2, VerseName = "Exodus 19:3-6", VerseNameAbrv = "Exo 19:3-6", VerseDescription = "The promise of YHVH, i.e. the Offer, is given to Israel", Commentary = "If Israel obeys the covenant, they shall be a peculiar treasure, a kingdom of priests for the nations", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Exo_19_7_to_8", ScriptureIdBeg = 2034, ScriptureIdEnd = 2035, BookID = 2, VerseName = "Exodus 19:7-8", VerseNameAbrv = "Exo 19:7-8", VerseDescription = "Offer accepted by Israel", Commentary = "By having an offer and an acceptance which the meetings of the minds gives us a contract/covenant", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Exo_20_16_to_21", ScriptureIdBeg = 2068, ScriptureIdEnd = 2073, BookID = 2, VerseName = "Exodus 20:16-21", VerseNameAbrv = "Exo 20:16-21", VerseDescription = "Not to bear false witness", Commentary = "An excellent quote from <b>Martin Luther</b> &quot;...[to] not deceitfully belie, betray, slander, nor defame our neighbor, but defend him, speak well of him, and <b>put the best construction on everything</b>&quot;.  See <sup>Deu 19:15-21, Jam 4:11</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Exo_21_5_to_6", ScriptureIdBeg = 2083, ScriptureIdEnd = 2084, BookID = 2, VerseName = "Exodus 21:5-6", VerseNameAbrv = "Exo 21:5-6", VerseDescription = "For the servant whose ear is bored", Commentary = "Is it required for the House of Israel to (at least symbolically) to become this type of servant", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Exo_31_12_to_17", ScriptureIdBeg = 2433, ScriptureIdEnd = 2438, BookID = 2, VerseName = "Exodus 31:12-17", VerseNameAbrv = "Exo 31:12-17", VerseDescription = "my Sabbaths ye shall keep", Commentary = "A blunt requirement for keeping the sabbath. It is a sign between Adonai and the children of Israel for ever", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Lev_19_17_to_18", ScriptureIdBeg = 3299, ScriptureIdEnd = 3300, BookID = 3, VerseName = "Leviticus 19:17-18", VerseNameAbrv = "Lev 19:17-18", VerseDescription = "Love thy neighbour as thyself", Commentary = "See <sup>Mat 22:37-40</sup> where Yeshua quotes this verse and ties it with the <i>shema</i>; see also the <b>royal law</b> <sup>Jam 2:8</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Lev_26_40_to_42", ScriptureIdBeg = 3565, ScriptureIdEnd = 3567, BookID = 3, VerseName = "Leviticus 26:40-42", VerseNameAbrv = "Lev 26:40-42", VerseDescription = "Confessing the iniquity of the Fathers", Commentary = "A remedy in the Torah for re-contracting with YHVY; See the article Confessions_per_Lev_26_40_thru_42_The_Iniquity_of_the_Fathers.pdf (Article ID 215)", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Num_13_31_to_32", ScriptureIdBeg = 4107, ScriptureIdEnd = 4108, BookID = 4, VerseName = "Numbers 13:31-32", VerseNameAbrv = "Num 13:31-32", VerseDescription = "The spies give an evil report", Commentary = "This evil report is a pattern for the bill of divorce which happens centuries latter with the House of Israel", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Deu_16_18_to_20", ScriptureIdBeg = 5361, ScriptureIdEnd = 5363, BookID = 5, VerseName = "Deuteronomy 16:18-20", VerseNameAbrv = "Deu 16:18-20", VerseDescription = "Justice Justice", Commentary = "Part of Due Process is to do justice justly", HasExtraInfo = false },

			new FavoriteVerse() { PartialView = "Deu_17_14_to_20", ScriptureIdBeg = 5379, ScriptureIdEnd = 5385, BookID = 5, VerseName = "Deuteronomy 17:14-20", VerseNameAbrv = "Deu 17:14-20", VerseDescription = "Prophecy for the 1<sup>st</sup> Samuel ch. 8 type of King",  Commentary = "&quot;...you say, &quot;I will set over me a king like all the nations that are  around me&quot;", HasExtraInfo = true },
//		new FavoriteVerse() { PartialView = "Deu_17_14_to_17", ScriptureIdBeg = 5379, ScriptureIdEnd = 5382, BookID = 5, VerseName = "Deuteronomy 17:14-17", VerseNameAbrv = "Deu 17:14-17", VerseDescription = "Prophecy for the 1<sup>st</sup> Samuel ch. 8 type of King", Commentary = "&quot;...you say, &quot;I will set over me a king like all the nations that are  around me&quot;", HasExtraInfo = true },

			new FavoriteVerse() { PartialView = "Deu_17_18_to_20", ScriptureIdBeg = 5383, ScriptureIdEnd = 5385, BookID = 5, VerseName = "Deuteronomy 17:18-20", VerseNameAbrv = "Deu 17:18-20", VerseDescription = "The King (The Sovereign) shall write a copy of the Torah", Commentary = "&quot;...<sup>18</sup> he shall write him a copy of this law&quot; (see also <sup>Jos 8:32</sup>)...<sup>20</sup> &quot;That his heart be not lifted up above his brethren...&quot;", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Deu_18_15_to_19", ScriptureIdBeg = 5400, ScriptureIdEnd = 5404, BookID = 5, VerseName = "Deuteronomy 18:15-19", VerseNameAbrv = "Deu 18:15-19", VerseDescription = "THE Prophet sent who is like God and Moses", Commentary = "Regardless of who <i><b>Ha</b>Navi</i> is, verses 15 and 18 could be interpreted as someone who is like God and like man", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Deu_18_20", ScriptureIdBeg = 5405, ScriptureIdEnd = 5405, BookID = 5, VerseName = "Deuteronomy 18:20", VerseNameAbrv = "Deu 18:20", VerseDescription = "The false prophet", Commentary = "The &quot;Greek Jesus&quot; as described by antinomian Christianity is a false prophet because he &quot;did a way with the law&quot;  see also <sup>Deu 13:1-11</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Deu_19_15", ScriptureIdBeg = 5422, ScriptureIdEnd = 5422, BookID = 5, VerseName = "Deuteronomy 19:15", VerseNameAbrv = "Deu 19:15", VerseDescription = "Truth as defined by Scripture", Commentary = "&quot;...at the mouth of two witnesses, or at the mouth of three witnesses, shall the matter be established.&quot;  See also <sup>Deu 17:6</sup>, <sup>Num 35:30</sup>, <sup>Mat 18:16</sup>, <sup>Joh 8:17</sup>, <sup>2Co 13:1</sup>, <sup>1Ti 5:19</sup>, <sup>Heb 10:28</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Deu_19_16_to_21", ScriptureIdBeg = 5423, ScriptureIdEnd = 5428, BookID = 5, VerseName = "Deuteronomy 19:16-21", VerseNameAbrv = "Deu 19:16-21", VerseDescription = "false witness and eye for an eye, tooth for tooth", Commentary = "Regarding truth, scriptures is far more interested in its application to conflict resolution and not about hypothetical and philosophical / theological dissertations (see SCOTUS decision in <b>Ashwander vs TVA</b>). The context of the definition of truth (Deu 19:15).  See Exo 20:16", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Deu_24_1_to_4", ScriptureIdBeg = 5527, ScriptureIdEnd = 5530, BookID = 5, VerseName = "Deuteronomy 24:1-4", VerseNameAbrv = "Deu 24:1-4", VerseDescription = "Bill of Divorce", Commentary = "Since this list is heavily geared towards <b>The House of Israel</b> and the fact that she was given a <b>Bill of Divorce</b>, it seemed prudent to include these relevant verses.  RSTNE: &quot;Only with the death of the husband can she remarry, which is why Yahshua died to release the bride back to the Father&quot;<sup>footnote 611<sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Psa_98_3", ScriptureIdBeg = 15494, ScriptureIdEnd = 15494, BookID = 19, VerseName = "Psalms 98:3", VerseNameAbrv = "Psa 98:3", VerseDescription = "Powerful words jam packed in one verse", Commentary = "<b>House of Israel</b> <i>scattered to the</i> ends of the earth, Standalone Aleph Tav <span class='at-red'>&#1488&#1461&#1514</span> next to <b>Salvation</b> from Elohim.  <br />Three verses down, Psa 98:6, it says to make a joyful noise to <span class='hebrew'>יהוה</span> <sup><b>Yehovah</b></sup>, <span class='hebrew'><span class='nrl'>הַ</span>מֶּלֶךְ</span> <sup><b>the King</b></sup>.", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Psa_122_1_to_9", ScriptureIdBeg = 16091, ScriptureIdEnd = 16099, BookID = 19, VerseName = "Psalms 122:1-9", VerseNameAbrv = "Psa 122:1-9", VerseDescription = "More on the covenant of ", Commentary = "See the article <u>Pray-for-the-peace-of-Jerusalem-Psa-122.pdf</u>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Isa_1_17_to_18", ScriptureIdBeg = 17672, ScriptureIdEnd = 17673, BookID = 23, VerseName = "Isaiah 1:17-18", VerseNameAbrv = "Isa 1:17-18", VerseDescription = "YHVH is a reasonable Elohim", Commentary = "To reason with Elohim is implies that an offer is being made by Elohim to Israel. The context of is pure religion see <sup>Isa 1:17</sup> and <sup>Jam 1:27</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Isa_2_3_to_4", ScriptureIdBeg = 17689, ScriptureIdEnd = 17690, BookID = 23, VerseName = "Isaiah 2:3-4", VerseNameAbrv = "Isa 2:3-4", VerseDescription = "Judgment of the Nations, swords beat into plowhsares", Commentary = "See the article <u>Prince-of-Peace-Sar-Shalom.doc</u>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Isa_9_6", ScriptureIdBeg = 17836, ScriptureIdEnd = 17836, BookID = 23, VerseName = "Isaiah 9:6", VerseNameAbrv = "Isa 9:6", VerseDescription = "Prince of Peace", Commentary = "For there to be a Prince of Peace <i>Sar Shalom</i>, it seems there would have to be a Peace Covenant/Contract", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Isa_11_11_to_13", ScriptureIdBeg = 17896, ScriptureIdEnd = 17898, BookID = 23, VerseName = "Isaiah 11:11-13", VerseNameAbrv = "Isa 11:11-13", VerseDescription = "Ephraim and Judah bury the hatchet", Commentary = "...&quot;Ephraim shall not envy Judah, and Judah shall not vex Ephraim&quot; <sup>Isa 11:13</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Isa_53_5_to_6", ScriptureIdBeg = 18717, ScriptureIdEnd = 18718, BookID = 23, VerseName = "Isaiah 53:5-6", VerseNameAbrv = "Isa 53:5-6", VerseDescription = "The suffering servant", Commentary = "What can I say but Wow! You just have to read the whole chapter.  Also notice a very powerful Standalone <span class=\"text-danger\">Aleph Tav</span> in <sup>Isa 53:6</sup>.  There is all kinds of legal nuances going on in this chapter but I want to focus in on <sup>Isa 53:5</sup> where this servant&quot;s suffering results in <b>peace</b>.  Who is it that needs a covenant of Peace but <b>the Lost Sheep of the House of Israel</b> who was given a <b>Bill of Divorce</b>.", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Jer_3_6_to_12", ScriptureIdBeg = 19009, ScriptureIdEnd = 19015, BookID = 24, VerseName = "Jeremiah 3:6-12", VerseNameAbrv = "Jer 3:6-12", VerseDescription = "Bill of Divorce", Commentary = "backsliding Israel committed adultery, put away, and given a bill of divorce", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Jer_31_31_to_34", ScriptureIdBeg = 19723, ScriptureIdEnd = 19726, BookID = 24, VerseName = "Jeremiah 31:31-34", VerseNameAbrv = "Jer 31:31-34", VerseDescription = "The renewed covenant is to both houses", Commentary = "Another powerful two house set of verses", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Eze_36_26_to_27", ScriptureIdBeg = 21386, ScriptureIdEnd = 21387, BookID = 26, VerseName = "Ezekiel 36:26-27", VerseNameAbrv = "Eze 36:26-27", VerseDescription = "New Heart, New Spirit, New Heart,", Commentary = "What an awesome spiritual upgrade!  By doing so, we will walk in his statutes and judgments.  See the standalone Aleph Tav in verse 37 between cause and my statutes ", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Eze_37_15_to_17", ScriptureIdBeg = 21413, ScriptureIdEnd = 21415, BookID = 26, VerseName = "Ezekiel 37:15-17", VerseNameAbrv = "Eze 37:15-17", VerseDescription = "The two sticks of Judah and Ephraim joined together in Elohim's hand", Commentary = "Another powerful two house set of verses", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Eze_37_26", ScriptureIdBeg = 21424, ScriptureIdEnd = 21424, BookID = 26, VerseName = "Ezekiel 37:26", VerseNameAbrv = "Eze 37:26", VerseDescription = "The covenant of peace", Commentary = "A covenant is a special form of contract, but a contract nonetheless therefore you need to view this from the perspective of law, see also <sup>Isa 11:13-14</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Hos_1_1_to_11", ScriptureIdBeg = 22096, ScriptureIdEnd = 22106, BookID = 28, VerseName = "Hosea 1:1-11", VerseNameAbrv = "Hos 1:1-11", VerseDescription = "The Bill of Divorce given to the House of Israel / &apos;Ephraim&apos;", Commentary = "Adonai has had enough as Ephraim has refused to take to heart the warnings given to her so the Bill of Divorce is her judgment and sentence.", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Hos_4_6", ScriptureIdBeg = 22140, ScriptureIdEnd = 22140, BookID = 28, VerseName = "Hosea 4:6", VerseNameAbrv = "Hos 4:6", VerseDescription = "&apos;My people are destroyed for lack of knowledge...&apos;", Commentary = "An oft quoted verse but only the first part is quoted not the rest.  The context of Hosea in the first chapter which describes the House of Israel getting the Bill of Divorce", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Mal_4_4_to_6", ScriptureIdBeg = 23143, ScriptureIdEnd = 23145, BookID = 39, VerseName = "Malachi 4:4-6", VerseNameAbrv = "Mal 4:4-6", VerseDescription = "Shomer the Law of Moses, Elijah the prophet, hearts turned", Commentary = "The 400 year gap of scripture from the Old Testament to the New.  As there is a Standalone Aleph Tav in the verse of the English Old Testament, there is also one in the last sentence", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Mat_5_17_to_20", ScriptureIdBeg = 23252, ScriptureIdEnd = 23255, BookID = 40, VerseName = "Matthew 5:17-20", VerseNameAbrv = "Mat 5:17-20", VerseDescription = "The Sermon on the Mount: The Law and the Prophets", Commentary = "These verses are found in the heart of the sermon on the mount where <i>Yeshua</i> is teaching the <b>Torah</b> and is at the heart of what <b>MHB</b> is all about.", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Mat_5_22_to_26", ScriptureIdBeg = 23257, ScriptureIdEnd = 23261, BookID = 40, VerseName = "Matthew 5:22-26", VerseNameAbrv = "Mat 5:22-26", VerseDescription = "One who has ought with your breather can not draw near with their <i>korban</i> offering", Commentary = "This is an advanced teaching", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Mat_10_5_to_7", ScriptureIdBeg = 23423, ScriptureIdEnd = 23425, BookID = 40, VerseName = "Matthew 10:5-7", VerseNameAbrv = "Mat 10:5-7", VerseDescription = "Yeshua commands the &apos;sent forth ones&apos; <sup>G649 <i>apostello</i></sup>) with a message", Commentary = "This begs the question, who are <b>The Lost Sheep of the House of Israel</b>? ", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Mat_15_24", ScriptureIdBeg = 23658, ScriptureIdEnd = 23658, BookID = 40, VerseName = "Matthew 15:24", VerseNameAbrv = "Mat 15:24", VerseDescription = "The identity of who Yeshua was sent for is given", Commentary = "...&apos;<span class=\"text-danger\">I am not sent but unto the <b>lost sheep of the house of Israel</b></span>&apos;.  Again, this begs the question, who are <b>The Lost Sheep of the House of Israel</b> and what is special about them?  More precisely what is special and unique about them from a legal status perspective?", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Mat_18_15_to_17", ScriptureIdBeg = 23743, ScriptureIdEnd = 23745, BookID = 40, VerseName = "Matthew 18:15-17", VerseNameAbrv = "Mat 18:15-17", VerseDescription = "The due process of in house conflict resolution", Commentary = "Yeshua gives us the process for resolving conflicts who are a member of your congregation", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Mat_18_18_to_20", ScriptureIdBeg = 23746, ScriptureIdEnd = 23748, BookID = 40, VerseName = "Matthew 18:18-20", VerseNameAbrv = "Mat 18:18-20", VerseDescription = "Binding in heaven and earth", Commentary = "This is a <b>&apos;400 level&apos;</b> advanced teaching describing &apos;vertical&apos; jurisdictions and authority.  It is about the dichotomy of the heavenly realm and the earthly realm, between private matters and public matters.  See <sup>Mat 16:19</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Mat_22_37_to_40", ScriptureIdBeg = 23910, ScriptureIdEnd = 23913, BookID = 40, VerseName = "Matthew 22:37-40", VerseNameAbrv = "Mat 22:37-40", VerseDescription = "The two great commandments given", Commentary = "How do you love the Messiah <sup>Joh 14:14</sup>, but to keep his commandments.  Yeshua gives us the two <b>great</b> commandments <sup>Lev 19:17-18</sup> and <sup>Deu 6:4-5</sup> and then says <span class=\"text-danger\">On these two commandments hang <b>all</b> the <b>law</b> and the <b>prophets</b></span>.  The same verbiage used in <sup>Mat 5:17</sup>", HasExtraInfo = false },

			new FavoriteVerse() { PartialView = "Joh_1_17", ScriptureIdBeg = 26062, ScriptureIdEnd = 26062, BookID = 43, VerseName = "John 1:17", VerseNameAbrv = "Joh 1:17", VerseDescription = "The law of Moses and the Grace of Yeshua?", Commentary = "This <i>but</i> is <b>butting</b> in! The but is added, and if removed, as it should be, the Torah compliments the grace and truth of the Messiah, if left in then it casts these ideas to be opposites of each other.  Moshe-Leads-you-to-Meshiach-Num-10-13, article #786", HasExtraInfo = false },

			new FavoriteVerse() { PartialView = "Joh_14_15", ScriptureIdBeg = 26684, ScriptureIdEnd = 26684, BookID = 43, VerseName = "John 14:15", VerseNameAbrv = "Joh 14:15", VerseDescription = "How to love Yeshua but to keep his commandments.", Commentary = "So what are his commandments? ", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Rom_1_1", ScriptureIdBeg = 27932, ScriptureIdEnd = 27932, BookID = 45, VerseName = "Romans 1:1", VerseNameAbrv = "Rom 1:1", VerseDescription = "Legal Status of Paul: Bond Servant of Yeshua Messiah", Commentary = "Romans 1:1-6 is Paul&quot;s calling card from which he is declaring is status.  If one were to ask Paul &quot;<i>Quo Warranto</i>&quot; (by what authority), could he not claim Exodus 21:5-6?", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Co1_7_20_to_24", ScriptureIdBeg = 28508, ScriptureIdEnd = 28512, BookID = 46, VerseName = "1 Corinthians 7:20-24", VerseNameAbrv = "1Co 7:20-24", VerseDescription = "Freeman, Paid for a Price", Commentary = "Marsing&quot;s maxim: The perceived paradox to become free you have to become a bond servant; see <sup>1Co 6:20<sup>", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Gal_3_28_to_29", ScriptureIdBeg = 29131, ScriptureIdEnd = 29132, BookID = 48, VerseName = "Galatians 3:28-29", VerseNameAbrv = "Gal 3:28-29", VerseDescription = "Seed of Abraham, heirs according to the promise", Commentary = "What does Paul mean when he says there is no distinction between Jew or Greek and how does this comport with Yeshua who said <span class=\"text-danger\">I am not sent but unto the <b>lost sheep of the house of Israel</b></span>&apos; <sup>Mat 15:24</sup> see also <sup>Mat 10:6</sup>", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Eph_2_12_to_19", ScriptureIdBeg = 29242, ScriptureIdEnd = 29249, BookID = 49, VerseName = "Ephesians 2:12-19", VerseNameAbrv = "Eph 2:12-19", VerseDescription = "Middle Wall of Partition Broken Down", Commentary = "To much to comment on, see the Extra Page", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Col_2_14", ScriptureIdBeg = 29509, ScriptureIdEnd = 29509, BookID = 51, VerseName = "Colossians 2:14", VerseNameAbrv = "Col 2:14", VerseDescription = "Handwriting of ordinances nailing it to his cross", Commentary = "To much to comment on, see the Extra Page", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Ti1_1_4", ScriptureIdBeg = 29701, ScriptureIdEnd = 29701, BookID = 54, VerseName = "1 Timothy 1:4", VerseNameAbrv = "1Ti 1:4", VerseDescription = "Word study of edifying", Commentary = "This word is <i>oikonomia</i> (Strong&quot;s <sup>G3622</sup>) which is where we get the word <b>economy</b><br />For more, see Economy-of-God-G3622-oikonomia-G3623-oikonomos-dispensation-steward.doc and The-Economy-of-God.doc", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Ti2_2_15", ScriptureIdBeg = 29843, ScriptureIdEnd = 29843, BookID = 55, VerseName = "2 Timothy 2:15", VerseNameAbrv = "2Ti 2:15", VerseDescription = "Study to show thyself approved", Commentary = "Two levels of study", HasExtraInfo = true },
			new FavoriteVerse() { PartialView = "Jam_1_27", ScriptureIdBeg = 30294, ScriptureIdEnd = 30294, BookID = 59, VerseName = "James 1:27", VerseNameAbrv = "Jam 1:27", VerseDescription = "Pure religion", Commentary = "The definition for <b>religion</b> as defined in scripture is found n this verse", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Pe1_2_9_to_10", ScriptureIdBeg = 30409, ScriptureIdEnd = 30410, BookID = 60, VerseName = "1 Peter 2:9-10", VerseNameAbrv = "1Pe 2:9-10", VerseDescription = "chosen generation, royal priesthood, holy nation (quote Hosea ch 1)", Commentary = "Whose Peters audience but to non other than the Lost Sheep of the House of Israel who were <i>Lo Ami</i> Not my People and  <i>Lo Ruchmah</i> no mercy See Hos 1:6-10", HasExtraInfo = false },
			new FavoriteVerse() { PartialView = "Rev_21_24_to_27", ScriptureIdBeg = 31078, ScriptureIdEnd = 31081, BookID = 66, VerseName = "Revelation 21:24-27", VerseNameAbrv = "Rev 21:24-27", VerseDescription = "Israel will judge the nations", Commentary = "The tribes of Israel, a Kingdom of priests <sup>Exo 19:6</sup>, will adjudicate any matter that they receive from the Non-Israelite nations. What is the role of a priest but to be an intercessor between the people (the nations) and Elohim.", HasExtraInfo = false }
			}.AsQueryable();
	}
}
